- name: install nginx playbook
  hosts: frontend # we should mention only one group here.
  become: yes # becoming root user
  tasks:
    - name: install nginx
      ansible.builtin.package:
        name: nginx
        state: present
    - name: start nginx
      ansible.builtin.service:
        name: nginx
        state: started
