- name: variables from files
  hosts: local
  connection: local
  vars_files: # vars from files
    - info.yaml
  tasks:
    - name: print information
      ansible.builtin.debug:
        msg: "{{ Village }}, {{ State }}, {{ Country }}"
