- name: vars from prompt
  hosts: local
  connection: local
  vars_prompt:
    - name: Username # variable name
      prompt: "enter user name"
      private: false
    - name: password
      prompt: "enter password"
      private: true # confidential information, the typed information will not be visible
  tasks:
    - name: print variables
      ansible.builtin.debug:
        msg: "{{ Username }} and {{ password }}"
