- name: loops playbook
  hosts: web2
  become: yes
  tasks:
    - name: print details
      ansible.builtin.package:
        name: { { item } }
        state: present
      loop:
        - git
        - zip
        - mysql
        - gcc
