- name: filters playbook
  hosts: local
  connection: local
  gather_facts: no
  tasks:
    - name: lower to upper case
      vars:
        username: Murali
      ansible.builtin.debug:
        msg: "{{ username | upper }}"
    - name: upper to lower
      vars:
        username: MURALI
      ansible.builtin.debug:
        msg: "{{ username | lower }}"
    - name: print min and max
      vars:
        numbers: [1, 30, 57, 87, 98, 46845]
      ansible.builtin.debug:
        msg: "{{ numbers | min }} and {{ numbers | max }}"
    - name: list to map
      vars:
        course:
          - { "key": "name", "value": "ansible" }
          - { "key": "duration", "value": "10hrs" }
          - { "key": "trainer", "value": "murali" }
      ansible.builtin.debug:
        msg: "{{ course | items2dict }}"
    - name: map to list
      vars:
        course:
          name: ansible
          duration: 10hrs
          trainer: murali
      ansible.builtin.debug:
        msg: "{{ course | dict2items }}"
    - name: string to list
      vars:
        fruits: "apple, banana, orange"
      ansible.builtin.debug:
        msg: "{{ fruits | split(',') }"
    - name: handle undefine variable
      ansible.bulitin.debug:
        msg: " {{ person | default('murali') }}"
    - name: check IP address is valid or not
      vars:
        ip: "192.168.1.1"
      ansible.buitin.debug:
        msg: " {{ ip | ansible.utils.ipaddr }}"
        #install netaddr libary to run this command.
        #pip3.9 install netaddr
        #packages in ansible will be installed using pip, since it is developed using python
