- name: shell and command module
  hosts: local
  connection: local
  gather_facts: no
  tasks:
    - name: ls command using shell module
      ansible.builtin.shell: ls -l >/tmp/output.txt

    - name: ls command using command module
      #ansible.builtin.command: ls -l >/tmp/output2.txt # error, since no access to redirections
      ansible.builtin.command: ls -l
      register: command_result #using register keyword will store the output of the command.

    - name: print the details
      ansible.builtin.debug:
        msg: "{{ command_result }}"
